/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Chapter = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'subtitle' : IDL.Text,
});

export const idlService = IDL.Service({
  'getChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Chapter = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  
  return IDL.Service({
    'getChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };